apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rollouts-app

resources:
- rollouts-app-ns.yaml
- rollouts-app-deploy.yaml
- rollouts-app-svc.yaml
- rollouts-app-config.yaml
